version: '3'

services:
  postgres:
    image: postgres:15.2
    ports:
      - "127.0.0.1:5432:5432"
    environment:
      - POSTGRES_PASSWORD=supcondev
      - POSTGRES_USER=supcondev
      - POSTGRES_DB=supcondev
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
