version: '3'

services:
  backend:
    working_dir: /home/node/supcon
    image: supcon_backend
    command: npm run start
    depends_on:
      - postgres
    networks:
      - backend
    volumes:
      - ./backend/config:/home/node/supcon/config
    ports:
      - 3000:3000

networks:
  backend: